name = "three-uniform-diaries"
version = "0.1.0"
defaultTargets = ["ThreeUniformDiaries"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "5bd58ac291422a21f412ae354c91e7d172255a2c"

[[require]]
name = "milliken"
git = "https://github.com/janhubicka/lean-milliken"
rev = "f607b613eae5b1e4a6b74f8579b6436b623d545e"

[[lean_lib]]
name = "ThreeUniformDiaries"
